### ISSUE TITLE
Modifica implementazione secret room

### ISSUE THREAD

**Issue by AciEsse** [andreascalzo99/ProgettoBlackFriendly#4]
Modificare la visibilità della stanza in modo tale da rendere accessibile solo dopo il push dell'oggetto libro presenta nella sala lettura.

**Comment by crigante** [comment]
Io ho sistemato l'implementazione ma ho fatto il push direttamente su master. Sorry

**Comment by AciEsse** [comment]
Nessun problema, ottimo lavoro!
